# Generated by Django 5.1.7 on 2026-03-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_pulse_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse',
            name='category',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
